// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/movie": {
            "get": {
                "description": "scrapes https://rottentomatoes.com/search url and returns the top result that matches title, year params provided",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "top search result scraped from rotten tomato",
                "parameters": [
                    {
                        "minLength": 1,
                        "type": "string",
                        "description": "movie title",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "maximum": 2023,
                        "minimum": 1972,
                        "type": "integer",
                        "description": "movie release year",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "title year",
                        "schema": {
                            "$ref": "#/definitions/rotten_tomato.RTMovieInfo"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "do ping",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "ping example",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "rotten_tomato.RTMovieInfo": {
            "type": "object",
            "properties": {
                "audienceScore": {
                    "$ref": "#/definitions/rotten_tomato.RTScore"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rating": {
                    "type": "string"
                },
                "runtime": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "tomatometerScore": {
                    "$ref": "#/definitions/rotten_tomato.RTScore"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "rotten_tomato.RTScore": {
            "type": "object",
            "properties": {
                "averageRating": {
                    "type": "string"
                },
                "bandedRatingCount": {
                    "type": "string"
                },
                "likedCount": {
                    "type": "integer"
                },
                "notLikedCount": {
                    "type": "integer"
                },
                "ratingCount": {
                    "type": "integer"
                },
                "reviewCount": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
